Add support for multiple monitors
wolfmanstout/talon-gaze-ocr pull request #31
Opened 2024-10-14 14:49 UTC by alexander-clarke

This is activated with two main talon settings, controlling if clamping occurs and the behaviour when there is no eye tracker data.

Addresses #29 & #30 , although there could be more options in terms of when to use different monitors

Only implemented for talon backend at the moment. Added to_rect and to_bounding box helper functions. It isn't the cleanest but wasn't sure the best way of handling the multiple backends and so left it a little messy as an initial commit but could be refactored.

2024-10-15 05:03 UTC, wolfmanstout requested changes
Thanks for writing this up! Are you finding that the fallback kicks in automatically when you look at your second monitor because the gaze is out of bounds? Or do you not use an eye tracker?

2024-10-16 05:43 UTC, wolfmanstout commented on gaze_ocr_talon.py
> +    type=str,
Use `type=Literal["active_window", "main_screen"]` and then you don't need to repeat that in the description.

2024-10-16 10:03 UTC, alexander-clarke commented on .subtrees/gaze-ocr/gaze_ocr/_gaze_ocr.py
> +    def __init__(self, ocr_reader: Reader, fallback_when_no_eye_tracker: str = "main_screen"):
Moved this to an enum now everywhere

2024-10-16 10:05 UTC, alexander-clarke commented on .subtrees/screen-ocr/screen_ocr/_screen_ocr.py
> +    def to_rect(bounding_box: BoundingBox) -> rect.Rect:
Moved the function definitions to an if and now outside the import section

2024-10-16 10:05 UTC, alexander-clarke commented on .subtrees/screen-ocr/screen_ocr/_screen_ocr.py
> +        if self._is_talon_backend():
Done

2024-10-16 10:05 UTC, alexander-clarke commented on .subtrees/screen-ocr/screen_ocr/_screen_ocr.py
> +            elif not bounding_box:
Done

2024-10-16 11:02 UTC, alexander-clarke commented on .subtrees/screen-ocr/screen_ocr/_screen_ocr.py
> +        clamp_to_main_screen: bool = True
The eye tracker can get some data on other screens, as long as they are right next to the main screen. It does get less accurate and won't work for the full width of other monitors. I realise now though that this setting here isn't doing much on it's own as there's another clamp to main monitor here: [talon.py](https://github.com/wolfmanstout/talon-gaze-ocr/blob/5d2b61ab026e4531b42341a7012aa9d1a7cd8494/.subtrees/gaze-ocr/gaze_ocr/talon.py#L201C1-L201C30)

The reason I'm not passing it dynamically is that I wanted a setting to clamp to main monitor based upon if people had their monitors next to each other and would want their searches to apply to these monitors next to each other, or just their main monitor. But maybe that should be a different setting to this as without removing that other clamp it doesn't do too much, and removing that other clamp would require more changes to not break everything

I have now moved it to passing it to the functions, but may revisit this with different logic later

2024-10-16 11:04 UTC, alexander-clarke commented on gaze_ocr_talon.py
> +    type=str,
Done, although made it screaming snake case to more match the enums being used, can make it back to regular snake case

2024-10-16 11:06 UTC, alexander-clarke commented
> Thanks for writing this up! Are you finding that the fallback kicks in automatically when you look at your second monitor because the gaze is out of bounds? Or do you not use an eye tracker?
Sometimes I use the eye tracker or not
When I do use the eye tracker: if I look to the right of my left monitor there is still some gaze information and it doesn't kick in, but if I look further left then it does kick in automatically as it loses that gaze information
It could have a smarter decision to start using the fallback, but implemented it like this for now

2024-10-16 11:07 UTC, alexander-clarke commented on .subtrees/screen-ocr/screen_ocr/_screen_ocr.py
> +    def to_bounding_box(rect_talon: rect.Rect)->BoundingBox:
Done

2024-10-17 14:39 UTC, wolfmanstout approved these changes

2024-10-17 14:40 UTC, merged